apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-phonebook-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/demo-phonebook-pv
    type: DirectoryOrCreate
