apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-phonebook-pvc
  namespace: demo-phonebook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
