apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-demo-deployment
  namespace: phone-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phone-demo
  template:
    metadata:
      labels:
        app: phone-demo
    spec:
      containers:
        - name: phone-demo
          image: phone-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: phone-app-config
            - secretRef:
                name: phone-app-secret
          volumeMounts:
            - name: phone-demo-storage
              mountPath: /data
      volumes:
        - name: phone-demo-storage
          persistentVolumeClaim:
            claimName: phone-demo-pvc
