apiVersion: v1
kind: PersistentVolume
metadata:
  name: phone-demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/phone-demo-data
  persistentVolumeReclaimPolicy: Retain
