apiVersion: v1
kind: Secret #kind of resource
metadata:
  name: address-book-secret #name of the secret
  namespace: add-book #namespace where this resource will be created
type: Opaque #type of the secret. Default is Opaque, which means it can store arbitrary data.
stringData:
  app.secret: "k8s-secret-demo"
