apiVersion: v1
kind: Service

metadata:
  name: nginx-service-port

spec:

  type: ClusterIP

  selector:
    app: nginx-port

  ports:

  # Clients connect using Port 8080
  - port: 8080

    # Traffic forwarded to Container Port 80
    targetPort: 80
