name: Build and Push Docker Image

on:
  push:
    branches:
      - feature/docker
  workflow_dispatch:

env:
  IMAGE_NAME: demo-repo
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: 
      - self-hosted
      - Linux
      - X64
      - GithubRunner

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -f docker-test/Dockerfile \
            docker-test

      - name: Save image as tar
        run: |
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  push:
    runs-on:
        - self-hosted
        - Linux
        - X64
        - GithubRunner
    needs: build

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load -i image.tar

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Tag image
        run: |
          docker tag \
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}