name: Terraform EKS Deployment

on:

  workflow_dispatch:

    inputs:

      action:

        description: "Select Terraform Action"

        required: true

        default: deploy

        type: choice

        options:
          - deploy
          - destroy


jobs:


  terraform:


    runs-on:
      - self-hosted
      - Linux
      - X64
      - GithubRunner


    defaults:

      run:

        working-directory: terraform-k8s


    steps:


      - name: Checkout Repository

        uses: actions/checkout@v4



      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3



      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ secrets.AWS_REGION }}



      - name: Terraform Init

        run: terraform init



      - name: Terraform Validate

        run: terraform validate



      - name: Terraform Plan Deploy

        if: inputs.action == 'deploy'

        run: terraform plan



      - name: Terraform Apply

        if: inputs.action == 'deploy'

        run: terraform apply -auto-approve



      - name: Terraform Plan Destroy

        if: inputs.action == 'destroy'

        run: terraform plan -destroy



      - name: Terraform Destroy

        if: inputs.action == 'destroy'

        run: terraform destroy -auto-approve